### ISSUE TITLE
Post content and post image is not showing in post details page... Magento version 2.1.7, i didn't install any other modules...

### ISSUE THREAD

**Issue by colaninfotech** [mageplaza/magento-2-blog#58]
### Preconditions

1. Magento: 
2. PHP: 
3. MySQL: 
4. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by Kenny1994** [comment]
Hi,

I have checked that issue and have no issues appear in post details page ( both content and image ). The timestamp function is working normally in Magento 2.1.7.
If you still have the problem, just send me your screenshot. I will check it again.
Here is my testing page http://prntscr.com/ffz10n
Thank you!

**Comment by shadowcomm** [comment]
Hello, we are having the same issue where I have installed the latest version of this software on our M2 application (2.1.6) and it seems MySQL is having an issue saving the data. Here is our blog page - https://www.ake.com/blog and we have 157 posts that will not save to the blogroll page - http://prntscr.com/fgzv0i - please advise, thank you.

**Comment by Kenny1994** [comment]
Hi shadowcomm,
I have fixed that issue. 
Please check mail and confirm that it is working normally
Tell me if you have any further problems.
Thank you!

**Comment by shadowcomm** [comment]
Thanks for the instruction. We’ve added the files and upgraded the module. Unfortunately, it overwrote our blog folder and broke our original layout, so we tried to revert back to the old one and that didn’t work either. 

You can have a look at what it did install here: https://www.ake.com/blog And if you look here https://www.ake.com/blog.html, it used to fit nicely into the page body with the posts on the left and the categories and recent posts on the right. 

Any further thoughts on how we may be able to restore?

**Comment by digitalredefned** [comment]
I upgraded to version 2.4.1 of the master branch and still experiencing the same issue on Magento 2.1.6

**Comment by digitalredefned** [comment]
Update - it is working properly however I had to go and save each individual post.

**Comment by Kenny1994** [comment]
Hi, digitalredefned

Is your mean importing posts function?
Currently, our blog module hasn't that feature but I will add in the next update patch.
Thank you!

**Comment by colaninfotech** [comment]
Thanks, it's working good! @Kenny1994

**Comment by digitalredefned** [comment]
@Kenny1994 - I'm talking about the update to fix the image and content not displaying on the post details page.  I updated to 2.4.1 and it didn't initially work.  However, after I went in and saved a post the content and image displayed.

**Comment by Kenny1994** [comment]
@shadowcomm Your problems have been fixed. Please check mail and confirm that it is working normally.
@digitalredefned When you update fixing patch, your OLD posts (which you saved to DB before) still not appear to the front end right?. Can you up several pictures about your problems for more detail.
